build: fix for platforms which disallow indirect linking
On Fedora 26, I had to add more explicit libs to pkg-config in order to
build rust-ffmpeg examples or any project based on rust-ffmpeg. Example
of error message:

note: /usr/bin/ld: /home/fengalin/Projects/rust-ffmpeg/target/debug/deps/libffmpeg-c448b252bca789ad.rlib(ffmpeg-c448b252bca789ad.0.o): undefined reference to symbol «av_frame_free@@LIBAVUTIL_55»
          //usr/lib64/libavutil.so.55: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status